

server:
    servlet:
        context-path: /
    port: 8888
spring:
    profiles:
        active: dev
        
        

        
mybatis:
    typeAliasesPackage: cn.ff.burning
    mapperLocations: classpath:mapper/*.xml
    configuration:
        map-underscore-to-camel-case: true
