

spring:
    
    datasource:
        #        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://47.93.246.239:3306/redseft?useUnicode=true&amp;characterEncoding=UTF-8&amp;useOldAliasMetadataBehavior=true&useSSL=false
        username: root
        password: redSoft!123
        type: com.alibaba.druid.pool.DruidDataSource
    redis:
        database: 3
        host: 47.92.192.78
        port: 6379
        password: redSoft_Java18&hrp
#        timeout:






security:
    jwt-header: Authorization
    jwt-prefix: Bearer
    jwt-secret: hadManyMoney
    jwt-expiration: 300 # 5 min
    un-check-url:
        - /noAuth/**
#        - /authorize/*
        - /error
    authentication-url-password: /authorize/login/password
    authentication-url-mobile: /authorize/login/mobile
    authentication-url-idcard: /authorize/login/idcard
    
    loginsource-web: OxDE6x1LNzG42tJ4ZGVLi0hURR
    loginsource-bgm: $2a$10$MhbAAOPMyOdubhQ7b55




logging:
    level:
        cn.ff.burning.mapper: debug

aliyun:
    mns:
        access-key-id: LTAIJMDwpxNMqxUk
        access-key-secret: BbP00DXKfHH4vG2XkUt4AgCPKZVkYm
        sign-name: 中科冠融科技有限公司

